#!/bin/sh
if [ "${1}" = "" ]; then
  echo "formating all"
  go vet -vettool="$(which shadow)" ./...
  go fmt ./...
else
  echo "formating ${1}"
  go vet -vettool="$(which shadow)" ./"${1}"/...
  go fmt ./"${1}"/...
fi
