// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pre-upload": {
            "post": {
                "description": "check quota and object details before upload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Objects"
                ],
                "summary": "HandlePreUpload",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.PreUploadObjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PreUploadObjectRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.PreUploadObjectReq": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "@inject_tag: json:\"key\"",
                    "type": "string"
                },
                "size": {
                    "description": "@inject_tag: json:\"size\"",
                    "type": "integer"
                },
                "user_id": {
                    "description": "@inject_tag: json:\"user_id\"",
                    "type": "string"
                }
            }
        },
        "api.PreUploadObjectRes": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "@inject_tag: json:\"key\"",
                    "type": "string"
                },
                "upload_id": {
                    "description": "@inject_tag: json:\"upload_id\"",
                    "type": "string"
                },
                "user_id": {
                    "description": "@inject_tag: json:\"user_id\"",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
